language: ruby
cache: bundler
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/activerecord-5.2.x.gemfile
  - gemfiles/activerecord-6.0.x.gemfile
addons:
  code_climate:
    repo_token:
      secure: Dn+nXUOFHTRUhYqYM1NYSxYSyoDhFaB2EHvlhBJ/FK3QxCy4a0beSLhs+YnDl8kI1DOrZQMl7HDrh9AHlfYvu5fX4zADD5g7JkTA2mIx1Rk3yazAUuy1j1ftX/UaowzoUAR5t0qwYm344Nnqoh+O1FujvWbiGVuZvWa6vfjFbXA=
matrix:
  fast_finish: true
before_install:
  - gem install bundler
sudo: false
